10 REM - THIS PROGRAM WAS CREATED BY LOUIS KRAIMER
20 REM - FOR DUNWOODY COLLEGE OF TECHNOLOGY'S
30 REM - COMPUTER TECHNOLOGY DEPARTMENT
40 PRINT "WELCOME TO DUNWOODY COLLEGE OF TECHNOLOGY!"
50 PRINT "WHAT PROGRAM ARE YOU INTERESTED IN?"
60 PRINT "TYPE CLDE FOR CLOUD ENGINEERING TECHNOLOGY";, A$
70 PRINT "TYPE CNTS FOR COMPUTER NETWORKING SYSTEMS", B$
80 PRINT "TYPE CWEB FOR WEB PROGRAMMING AND DATABASE DEVELOPMENT", C$
90 IF A$="CLDE" THEN GOTO 100
92 IF A$="CNTS" THEN GOTO 200
94 IF A$="CWEB" THEN GOTO 300
100
200
300
400